repos:
  - repo: builtin
    hooks:
      - id: check-merge-conflict
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        exclude: '^.+/day.+\.txt$'
      - id: end-of-file-fixer
